const fileInput=document.getElementById('fileInput');const dropzone=document.getElementById('dropzone');const fileList=document.getElementById('fileList');const uploadBtn=document.getElementById('uploadBtn');const query=document.getElementById('query');const searchBtn=document.getElementById('searchBtn');const results=document.getElementById('results');const apiUrlInput=document.getElementById('apiUrl');const apiStatus=document.getElementById('apiStatus');let selected=[];
const savedApi=localStorage.getItem('bibliotecarioApi')||'';if(apiUrlInput)apiUrlInput.value=savedApi;
function apiBase(){return (apiUrlInput?.value||'').trim().replace(/\/$/,'')}
async function checkApi(){const base=apiBase();if(!base){apiStatus.textContent='API: pendiente de conectar';return}apiStatus.textContent='Comprobando backend…';try{const r=await fetch(`${base}/api/health`);const data=await r.json();if(!r.ok||!data.ok)throw new Error(data.ollama?.error||'Backend no listo');apiStatus.textContent=`API conectada · Ollama OK · ${data.embedding_model}`}catch(e){apiStatus.textContent='API configurada, pero el backend no está listo'}}
function saveApi(){const value=apiBase();if(value)localStorage.setItem('bibliotecarioApi',value);else localStorage.removeItem('bibliotecarioApi');checkApi()}
function renderFiles(){fileList.innerHTML=selected.map(f=>`<div class="file">📄 ${escapeHtml(f.name)} <span style="opacity:.6">(${Math.round(f.size/1024)} KB)</span></div>`).join('');uploadBtn.disabled=!selected.length}
function setFiles(files){selected=[...files].filter(f=>/\.(md|docx|txt)$/i.test(f.name));renderFiles()}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
fileInput.addEventListener('change',e=>setFiles(e.target.files));['dragenter','dragover'].forEach(x=>dropzone.addEventListener(x,e=>{e.preventDefault();dropzone.classList.add('drag')}));['dragleave','drop'].forEach(x=>dropzone.addEventListener(x,e=>{e.preventDefault();dropzone.classList.remove('drag')}));dropzone.addEventListener('drop',e=>setFiles(e.dataTransfer.files));
apiUrlInput?.addEventListener('change',saveApi);
uploadBtn.addEventListener('click',async()=>{const base=apiBase();if(!base){alert('Primero configura la URL HTTPS de la API.');return}uploadBtn.disabled=true;apiStatus.textContent='Subiendo e indexando…';try{for(const file of selected){const form=new FormData();form.append('file',file);const r=await fetch(`${base}/api/upload`,{method:'POST',body:form});if(!r.ok)throw new Error(await r.text())}apiStatus.textContent=`${selected.length} archivo(s) indexado(s) correctamente`;selected=[];renderFiles();checkApi()}catch(e){apiStatus.textContent='Error al conectar con la API';alert(`No se pudo indexar: ${e.message}`)}finally{uploadBtn.disabled=!selected.length}});
async function search(){const q=query.value.trim();const base=apiBase();if(!q)return;if(!base){results.className='results';results.innerHTML='<p>Configura primero la URL HTTPS de la API.</p>';return}results.className='results';results.innerHTML='<p>Buscando en la biblioteca…</p>';try{const r=await fetch(`${base}/api/search?q=${encodeURIComponent(q)}`);if(!r.ok)throw new Error('API no disponible');const data=await r.json();const items=data.results||[];results.innerHTML=items.length?items.map(x=>`<div class="result"><small>${escapeHtml(x.source||'Biblioteca')}</small><p>${escapeHtml(x.content||'')}</p></div>`).join(''):'<p>No se encontraron fragmentos relevantes.</p>'}catch(e){results.innerHTML='<p>La API no responde. Comprueba que el backend esté activo y que la URL HTTPS sea correcta.</p>'}}
searchBtn.addEventListener('click',search);query.addEventListener('keydown',e=>{if(e.key==='Enter')search()});checkApi();